# This Dockerfile was generated.
# Do not manually update this file; changes will be lost.
FROM python:{{ .FromVersion }}

LABEL maintainer="Julien Klaer"
{{ if eq .ImageVariant "alpine3.16" -}}
    RUN apk add gcc libc-dev
{{- end }}
RUN pip install poetry=={{ .PoetryVersion }} && \
    poetry config virtualenvs.in-project true

CMD ["poetry", "--version"]
