name: Docker images

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

env:
  DOCKER_BASE_IMAGE_NAME: madjlzz/python-poetry

jobs:

  build_image_120:
    name: Build Docker images for Poetry 1.2.0
    runs-on: ubuntu-latest
    env:
      POETRY_VERSION: 1.2.0

    strategy:
      matrix:
        python-version: [ 3.10.6, 3.9.13 ]
        image-variant: [ alpine3.16, bullseye, buster, slim-bullseye, slim-buster ]

    steps:
      - name: Clone git repository
        uses: actions/checkout@v3

      - name: Build the Docker image
        run: |
          image="${DOCKER_BASE_IMAGE_NAME}-${POETRY_VERSION}"
          tag="${POETRY_VERSION}-${matrix.python-version}-${matrix.image-variant}"
          docker build . --file "${POETRY_VERSION}/${matrix.python-version}/${matrix.image-variant}/Dockerfile" --tag ${image}:${tag}
          docker image ls

#  build_image_1115:
#    name: Build Docker images for Poetry 1.1.15
#    runs-on: ubuntu-latest
#    env:
#      POETRY_VERSION: 1.1.15
#
#    strategy:
#      matrix:
#        python-version: [ 3.10.6, 3.9.13 ]
#        image-variant: [alpine3.16, bullseye, buster, slim-bullseye, slim-buster]