name: Docker images

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

env:
  DOCKER_BASE_IMAGE_NAME: ghcr.io/madjlzz/python-poetry

jobs:

  build_image_120:
    name: Build Docker images for Poetry 1.2.0
    runs-on: ubuntu-latest
    env:
      POETRY_VERSION: 1.2.0

    strategy:
      fail-fast: false
      matrix:
        PYTHON_VERSION: [ 3.10.6, 3.9.13 ]
        IMAGE_VARIANT: [ alpine3.16, bullseye, buster, slim-bullseye, slim-buster ]

    steps:
      - name: Clone git repository
        uses: actions/checkout@v3

      - name: Build an push the Docker image
        env:
          DOCKER_USERNAME: madjlzz
          IMAGE_DOCKERFILE: ${{ env.POETRY_VERSION}}/${{ matrix.PYTHON_VERSION }}/${{ matrix.IMAGE_VARIANT }}/Dockerfile
          IMAGE_NAME: ${{ env.DOCKER_BASE_IMAGE_NAME }}-${{ env.POETRY_VERSION}}
          IMAGE_TAG: ${{ matrix.PYTHON_VERSION }}-${{ matrix.IMAGE_VARIANT }}
        run: |
          docker build . --file ${IMAGE_DOCKERFILE} --tag ${IMAGE_NAME}:${IMAGE_TAG}
          docker image ls
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${DOCKER_USERNAME}" --password-stdin
          docker push ${IMAGE_NAME}:${IMAGE_TAG}        

  build_image_1115:
    name: Build Docker images for Poetry 1.1.15
    runs-on: ubuntu-latest
    env:
      POETRY_VERSION: 1.1.15

    strategy:
      fail-fast: false
      matrix:
        PYTHON_VERSION: [ 3.10.6, 3.9.13 ]
        IMAGE_VARIANT: [ alpine3.16, bullseye, buster, slim-bullseye, slim-buster ]

    steps:
      - name: Clone git repository
        uses: actions/checkout@v3

      - name: Build an push the Docker image
        env:
          DOCKER_USERNAME: madjlzz
          IMAGE_DOCKERFILE: ${{ env.POETRY_VERSION}}/${{ matrix.PYTHON_VERSION }}/${{ matrix.IMAGE_VARIANT }}/Dockerfile
          IMAGE_NAME: ${{ env.DOCKER_BASE_IMAGE_NAME }}-${{ env.POETRY_VERSION}}
          IMAGE_TAG: ${{ matrix.PYTHON_VERSION }}-${{ matrix.IMAGE_VARIANT }}
        run: |
          docker build . --file ${IMAGE_DOCKERFILE} --tag ${IMAGE_NAME}:${IMAGE_TAG}
          docker image ls
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${DOCKER_USERNAME}" --password-stdin
          docker push ${IMAGE_NAME}:${IMAGE_TAG}    
